/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_sunqi13_com_fabricndkdemo_HellJNI */

#ifndef _Included_demo_sunqi13_com_fabricndkdemo_HellJNI
#define _Included_demo_sunqi13_com_fabricndkdemo_HellJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_sunqi13_com_fabricndkdemo_HellJNI
 * Method:    AddC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_demo_sunqi13_com_fabricndkdemo_HellJNI_AddC
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
